### DISCUSSION TITLE
Hosting Frontend and Pocketbase on the same server results in error

### DISCUSSION THREAD

**Discussion by ghost** [pocketbase/pocketbase#1517] [Q&A] [answered]
Broad title but I dont know how to summarize this better.   
The error I'm facing is:
`GET http://localhost:8090/api/collections/songs/records?page=1&perPage=200 net::ERR_CONNECTION_REFUSED
`

I'm running a angular frontend, pocketbase and nginx proxy manager dockered. The frontend has a SSL certificate. Pocketbase is running on the same docker network as the frontend.

Now the issue I'm facing from my development computer the site works. It is hosted on an oracle vps and works with my local dev pc. It does **not** work with my macbook, there I get the error above.

I'm lost how the site can have two different behaviors when its all remote...

This is my proxy:
![grafik](https://user-images.githubusercontent.com/10931525/211127822-bbd8b9f8-a864-4bfa-9d00-67ab402c0694.png)

This is my docker-compose.yml:
```yaml
version: "3.9"
services:
  frontend:
    hostname: frontend
    container_name: "frontend"
    image: "lagerfeuer:latest"
    networks:
      - magnet
    ports:
      - "3000:3000"

  pocketbase:
    hostname: pocketbase
    container_name: "pocketbase"
    image: ghcr.io/muchobien/pocketbase:latest
    restart: always
    command:
      - pocketbase
      - serve
      - --dir
      - /data
    ports:
      - "8090:8090"
    volumes:
      - ./pocketbase:/data
    networks:
      - magnet

  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    networks:
      - magnet
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
networks:
  magnet:
    external: true
```

This is how I call the api:

```Typescript
    const pb = new PocketBase('http://localhost:8090');
    try {
      const record = await pb.collection('songs').getFullList();
}catch(err){
      console.log(err)
}
```

Let me know if I can provide more infos
