### DISCUSSION TITLE
Write-Ahead Logging mode in Docker environment - potential data loss

### DISCUSSION THREAD

**Discussion by m4rcelpl** [pocketbase/pocketbase#1558] [Q&A]
Hi!

Pocketbase v0.11.0
Hosted on Docker from this image ghcr.io/muchobien/pocketbase:latest

Today i log on on admin panel, make new table and upload data thru api. A few minutes later, it turned out that the docker server needed to be restarted. After reboot it turned out, that there are no my changes and new table. From what I checked, any changes are saved in temporary files (db-wal) as Write-Ahead Logging mode. I don't know why restarting the docker server resulted in data loss. I have directories joined by local files:
```
volumes:
       - /shared/pocketbase_prod/data:/pb_data
       - /shared/pocketbase_prod/public:/pb_data
```
Does anyone have an idea how to avoid such situations? Currently, any failure can result in data loss. Is it possible to change the database operation mode with some variables so that it saves changes immediately? I am aware that it will reduce its performance but in my case it is not crucial.

**Comment by ganigeorgiev** [comment]
I don't think this is related to the WAL mode. The `-wal` file is stored alongside the main db file and as long as your `pb_data` is stored on a persistent storage, your app data also should persist.

The issue is most likely caused by incorrectly mounted volume(s). I'm not sure that I understand the above `volumes` example and why you are mounting 2 directories in one `pb_data`. You can ssh your container and double check whether all expected directories/files are mounted properly.

**Reply by m4rcelpl** [reply]
You are right there is little mistake. It should be like this:

volumes:
       - /shared/pocketbase_prod/data:/pb_data
       - /shared/pocketbase_prod/public:**/pb_public**

But that's not the problem, completely remove the link to the public folder. I was able to reproduce the "error". Just run pocketbase as a container, make some changes to the database, for example, create a new table, then restart the container and the table is gone.

**Reply by ganigeorgiev** [reply]
Could you provide your docker-compose file?

**Reply by m4rcelpl** [reply]
Yes!
```
version: "3.7"
services:
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: pocketbase
    restart: unless-stopped
    ports:
      - "8090:8090"
    volumes:
      - /shared/pocketbase_prod/data:/pb_data
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
```
