### DISCUSSION TITLE
Downloading pb_data from fly.io fails

### DISCUSSION THREAD

**Discussion by brucewayyn** [pocketbase/pocketbase#2187] [Q&A] [answered]
I ran these commands:
```bash
flyctl ssh issue --agent

flyctl proxy 10022:22
```
and then in a new terminal:
```bash
scp -r -P 10022 root@localhost:/pb/pb_data /pb_data
```
This is what I get in the terminal:
```bash
scp: mkdir /pb_data: Read-only file system
```
Did I miss a step?

**Comment by ganigeorgiev** [comment, marked as answer]
The last scp argument is the "destination" path, aka. the directory where the remote `pb_data` files will be downloaded.

Do you have a `/pb_data` directory on you local filesystem?

**Reply by brucewayyn** [reply]
It worked when I added a dot `.` before the local destination:
```bash
scp -r -P 10022 root@localhost:/pb/pb_data ./pb_data
```
I didn't have the directory and it made one, very clean and solid. Thank you, the docs are really well so it was only a matter of a `.`.

I am upgrading PocketBase to `0.14.0`, so now that I have my backup on local disk. I updated the docerfile:
```dockerfile
ARG PB_VERSION=0.14.0
```
I haven't touched the `fly.toml` since I only want to upgrade PocketBase. Should I only run `flyctl deploy`, and then run:
```bash
scp -r -P 10022 ./pb_data root@localhost:/pb/pb_data
```
Just want to make sure I am not missing a step. Thank you!

**Reply by ganigeorgiev** [reply]
There is no need for the restore step. Use it only if something goes terribly wrong (eg. you accidentally delete the volume).

`flyctl deploy` should be enough. The migrations will be applied automatically in a transaction with the new version start. If the deploy fail for some reason you can revert your DockerFile and redeploy with the old PocketBase version.

If you are changing your Dockerfile make sure that `PB_VERSION` is not overwritten in your fly.toml (otherwise, change the `PB_VERSION` in the fly.toml instead).

**Reply by brucewayyn** [reply]
The reason I changed `PB_VERSION` in `dockerfile` is because I don't have it in `fly.toml`, here is how `fly.toml` look:
```toml
app = "app-name"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "ams"
processes = []

[env]

[experimental]
  auto_rollback = true

[mounts]
  destination = "/pb/pb_data"
  source = "pb_data"

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
```
