### DISCUSSION TITLE
Running Multiple Pocketbase Containers - sharing data?

### DISCUSSION THREAD

**Discussion by splashsky** [pocketbase/pocketbase#2987] [Q&A] [answered]
Hey there! I have a single server that I run my projects on, and so I wanted to be able to spin up multiple backends for my various projects. I have a basic docker-compose file based on [muchobien's file](https://github.com/muchobien/pocketbase-docker/tree/main) that works for my first instance of Pocketbase. However, when I spun up another instance, it seems to share the data with the first instance despite the two having different logical volumes (one is set to /srv/first and the other /srv/second, for example).

Am I trying to run multiple instances incorrectly? Why are the two sharing the same data despite being set to different directories?

![image](https://github.com/pocketbase/pocketbase/assets/12104206/65aa1778-b927-49ad-a19f-7af11c41be29)
![image](https://github.com/pocketbase/pocketbase/assets/12104206/11b60841-cc0b-43b6-a121-1c968b182efd)
![image](https://github.com/pocketbase/pocketbase/assets/12104206/1fad4325-e7b4-4c2e-b57e-6d33aaad4968)

**Comment by ganigeorgiev** [comment, marked as answer]
Could you share your `docker-compose.yml`?

As long as the two containers have different mounted `pb_data` volume, the two instance should work independently one of another. Here is a minimal example based on the linked image readme:

```yml
version: "3.7"
services:
  pocketbase1:
    image: ghcr.io/muchobien/pocketbase:latest
    restart: unless-stopped
    ports:
      - "8091:8090"
    volumes:
      - ./pb_data1:/pb_data
  pocketbase2:
    image: ghcr.io/muchobien/pocketbase:latest
    restart: unless-stopped
    ports:
      - "8092:8090"
    volumes:
      - ./pb_data2:/pb_data
```

**Comment by splashsky** [comment]
Ah, so this would explain it. My inexperience with Docker is showing; I have two directories, each with their own docker-compose.yml, each defining the same setup but with different volumes.

```yml
version: "3.7"
services:
  pocketbase:
    image: pocketbase
    build:
      context: .
    container_name: db-sharkk
    restart: unless-stopped
    ports:
      - "8090:8080"
    volumes:
      - /srv/db-sharkk/data:/pb_data
      - /srv/db-sharkk/public:/pb_public
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
```

Since I only changed the container_name and volumes, I'd have to guess having the same service name was my primary problem
