### DISCUSSION TITLE
How can I use environment variables inside event hooks?

### DISCUSSION THREAD

**Discussion by sergio9929** [pocketbase/pocketbase#3243] [Q&A] [answered]
I would like to know how to use environment variables inside migrations and event hooks. I've tried `$os.getenv('CUSTOM_URL')` and `process.env.CUSTOM_URL` in both, but neither works.

I'm doing this to configure a docker with environment variables.

**Comment by ganigeorgiev** [comment]
`process.env.*` should work inside JS migrations as long as the user started the process has access to the env variables.

The `$os.*` bindings are currently not enabled for the JS migrations (they will be available with the next v0.18.0 release; _[see the note in master](https://github.com/pocketbase/pocketbase/blob/b4cb35483b85733e899769d17802986958001dde/plugins/jsvm/jsvm.go#L164)_).

Both should work in a `pb_hooks` context.

If you are not able to make it work with `process.env.*`, please elaborate more about your setup and/or provide some reproducible steps.

**Comment by sergio9929** [comment]
Thank you for the quick response.

If this isn't enough I can give you a proper reproduction later today.

## Setup:

file structure:
```txt
pocketbase.exe
pb_hooks
  - defaults.pb.js
  - history.pb.js
  - mails.pb.js
  - .env
pb_migrations
  - 1690927136_collections_snapshot..js
  - 1690928001_initial_settings.js
  - .env
.env
``` 
I put multiple .env files just in case.

Migration file:
```js
/// <reference path="../pb_data/types.d.ts" />
migrate((db) => {
  const dao = new Dao(db);

  const settings = dao.findSettings()
  settings.meta.appName = 'Example'
  settings.meta.appUrl = process.env.APP_URL || 'https://d.thelastdock.com/nmt'
  settings.logs.maxDays = 5

  settings.meta.senderName = 'Support'
  settings.meta.senderAddress = 'support@example.com'
  settings.smtp.enabled = true
  settings.smtp.host = 'example'
  settings.smtp.port = '1025'

  dao.saveSettings(settings)

  const admin = new Admin();
  admin.email = 'test@example.com'
  admin.setPassword('123123123')

  dao.saveAdmin(admin)
}, (db) => {
  return null
})
```

.env file
```env
APP_URL=https://example.com
```

## Docker

docker-compose.yml
```yml
version: "3.7"
services:
  pocketbase:
    image: spectado/pocketbase:0.17.7
    restart: unless-stopped
    ports:
      - "8090:80"
    environment:
      - APP_URL=https://example.com
    volumes:
      - ./db/pb_data:/pb_data
      - ./db/pb_migrations:/pb_migrations
      - ./db/pb_hooks:/pb_hooks

  node:
    image: node:20
    user: "node"
    working_dir: /home/node/app
    ports:
      - "3000:3000"
    environment:
      - NUXT_APP_BASE_URL=/
      - NUXT_PUBLIC_PB_SERVER_URL=http://pocketbase:80
      - NUXT_PUBLIC_PB_CLIENT_URL=http://127.0.0.1:8090
      - NODE_ENV=production
    volumes:
      - .output/:/home/node/app
    command: "node ./server/index.mjs"
```
