### DISCUSSION TITLE
How to run Pocketbase inside Devcontainers?

### DISCUSSION THREAD

**Discussion by kosperera** [pocketbase/pocketbase#3246] [Q&A] [answered]
I am trying to find a way to run Pocketbase inside my Golang @devcontainers. A typical use case would be, to tell the `docker-compose.yml` to:
- Spin up Golang dev environment using the official Golang Docker Image, and
- Spin up Pocketbase from a Docker Image, but mount the database and other files that reside locally in `db` folder.

Example project layout.
```zsh
.devcontainer/
  - devcontainer.json   # points to docker-compose, vscode settings, extensions, et al.
  - docker-compose.yml  # spin up golang:bullseye latest, mount workspaces folder to ../
cmd/
db/                     # database files, migrations, et al.
internal/
.gitignore
.editorconfig
```

**Comment by ganigeorgiev** [comment]
How you are planning to use PocketBase - directly as prebuilt executable or you want to extend it with Go or JS?

If the latter, note that PocketBase is distributed as regular Go package. To use it you have to import it in your Go file(s) - see https://pocketbase.io/docs/go-overview/.

If you just want to use the prebuilt executable (aka. the binary generated from `example/base/main.go`), you can check the example docker image in https://pocketbase.io/docs/going-to-production/#using-docker.

To specify a different directory for the database you can use the `--dir` flag.
When using Go, the migration are embedded in the final executable because they are regular Go files.
When using JS, the migrations are stored in a `pb_migrations` dir (you can set a different one with `--migrationsDir` flag).

For more details, please check https://pocketbase.io/docs/use-as-framework/.

If the above doesn't help, please elaborate because I don't understand what you are trying to do.

**Reply by kosperera** [reply]
I believe it's the latter (aka. the prebuilt executable using docker). I was referring to the devcontainer templates:
- https://github.com/devcontainers/templates/tree/main/src/javascript-node-postgres
- https://github.com/devcontainers/templates/tree/main/src/go-postgres

Instead of using `progress` in the above templates, I would like to replace it with pocketbase and then build the JavaScript-based client app (or go services) that uses pocketbase on GitHub Codespaces or VS Code Remote Containers.

**Reply by ganigeorgiev** [reply, marked as answer]
If you want to use the prebuilt executable, you don't have to install Go or anything in addition because the binary is statically linked.

If you want the executable to be part of your docker-compose services configuration you can use the [example Dockerfile from the docs](https://pocketbase.io/docs/going-to-production/#using-docker) and then define in your services config something like:

```yaml
services:
  pocketbase:
    build:
      context: ./ # uses the local Dockerfile, but you can replace it with an image
    ports:
      - "8080:8080"
    volumes:
      - ./pb_data:/pb/pb_data
      # either copy in the image or mount as volumes
      # - ./pb_migrations:/pb/pb_migrations
      # - ./pb_hooks:/pb/pb_hooks

  ...
```
