### DISCUSSION TITLE
Self host with Docker and Docker Compose

### DISCUSSION THREAD

**Discussion by zRafaF** [pocketbase/pocketbase#3279] [Show and tell]
This discussion gather the experience I got after selfhosting PocketBase for myself.

## 1. Create the PocketBase Dockerfile:
``` dockerfile
FROM alpine:latest

ARG PB_VERSION=0.18.1

RUN apk add --no-cache \
    unzip \
    ca-certificates

# download and unzip PocketBase
ADD https://github.com/pocketbase/pocketbase/releases/download/v${PB_VERSION}/pocketbase_${PB_VERSION}_linux_amd64.zip /tmp/pb.zip
RUN unzip /tmp/pb.zip -d /pb/

# uncomment to copy the local pb_migrations dir into the image
# COPY ./pb_migrations /pb/pb_migrations

# uncomment to copy the local pb_hooks dir into the image
# COPY ./pb_hooks /pb/pb_hooks

VOLUME /pb/pb_data
EXPOSE 8080

# start PocketBase
CMD ["/pb/pocketbase", "serve", "--http=0.0.0.0:8080"]
```

## Build Docker image
1. [Install Docker](https://docs.docker.com/get-docker/) on your machine.
2. Build your container: `docker build -t [my_container_name] .`.
3. Run your container: `docker run -p 8080:8080 [my_container_name]`.

You can view your created images with `docker images`.

### GitHub Actions CI
Have a look at [https://github.com/ZRafaF/educa-utf-db/blob/main/.github/workflows/publish-container.yml](https://github.com/ZRafaF/educa-utf-db/blob/main/.github/workflows/publish-container.yml) for an example of auto building and publishing image to DockerHub.

> This step is only a suggestion.
> This CI auto tags the release based on the name of the pull-request

## Docker Compose
The following docker compose pulls an image from DockerHub and starts it.

On a file named `docker-compose.yaml` paste:
``` yaml
version: "3.7"

services:
    pocketbase:
        image: [your image]  # place your image here
        restart: unless-stopped
        ports:
            - 8080:8080
        volumes:
            - "./pocketbase-data:/pb/pb_data"  # Attaches pb_data to a volume named 'pocketbase-data' on your current directory
```

## Deploying 
1. Navigate into the directory where your `docker-compose.yaml` is located.
2. Run `docker compose up -d`.
