### DISCUSSION TITLE
failed to create a temp dir: mkdir pb_data/.pb_temp_to_delete

### DISCUSSION THREAD

**Discussion by khrome83** [pocketbase/pocketbase#3385] [Q&A] [answered]
@ganigeorgiev this still appears to be some type of issues.

I failed to create a temp dir: mkdir pb_data/.pb_temp_to_delete: operation not permitted

Pocketbase version - [PocketBase v0.18.6](https://github.com/pocketbase/pocketbase/releases)

I am thinking this is not a permissions issue with PocketBase, because the `pb_data` folder was created by PocketBase (I think). 

What I am wondering is if the LiteFS FUSE file system is preventing this from being created. 
In my `litefs.yml` file you can see that this directory is specified. 

```yml
# The fuse section describes settings for the FUSE file system. This file system
# is used as a thin layer between the SQLite client in your application and the
# storage on disk. It intercepts disk writes to determine transaction boundaries
# so that those transactions can be saved and shipped to replicas.
fuse:
  dir: "/pb_data"
```

As you can see the permissions are permissive.
```cli
drwxrwxrwx    1 root     root             0 Sep 25 20:41 pb_data
drwxr-xr-x    2 root     root          4096 Sep 25 20:40 pb_migrations
```

Suggestions? Is there a way to change the location that backup files write too? I tried the TMPDIR option, and writing to `/tmp` but didn't see any results. 

This is in a Dockerfile, hosted on fly.io (so VM not container).

```Dockerfile
# Build our application using a Go builder.
FROM golang:1.20 AS builder
WORKDIR /go/src/app

COPY . .
RUN go build -buildvcs=false -ldflags "-s -w -extldflags '-static'" -tags osusergo,netgo -o /usr/local/bin/pocketbase ./

# Our final Docker image stage starts here.
FROM alpine:latest AS runtime
ARG LITEFS_CONFIG=litefs.yml

# Copy binaries from the previous build stages.
COPY --from=builder /usr/local/bin/pocketbase /usr/local/bin/pocketbase
COPY --from=flyio/litefs:0.5.5 /usr/local/bin/litefs /usr/local/bin/litefs

# Copy needed LiteFS configurations
ADD /etc/${LITEFS_CONFIG} /etc/litefs.yml

# Setup our environment to include FUSE & SQLite. We install ca-certificates
# so we can communicate with the Consul server over HTTPS. cURL is added so
# we can call our HTTP endpoints for debugging.
RUN apk add bash fuse3 sqlite ca-certificates curl

# Copy migrations from local directory to container
COPY ./migrations /pb_migrations

# Run LiteFS as the entrypoint. After it has connected and sync'd with the
# cluster, it will run the commands listed in the "exec" field of the config.
#ENTRYPOINT litefs mount
ENTRYPOINT litefs mount
```

Suggestions? I do have LiteFS Cloud, but I was hoping to use this as a longer term (slower cadence) backup as a just-in-case.

**Comment by ganigeorgiev** [comment]
It is most likely the LiteFS directory mount causing it to fail but I'm not sure that I understand fully the above Dockerfile to try to reproduce it.

Do you have a fly volume mounted in `/pb_data`? Why do you need the extra go build tags? Where do you start the PocketBase process (is it as part of the litefs exec config?)?

> Is there a way to change the location that backup files write too?

No. Backups are stored either locally in `pb_data/backups` or in S3.
The local temp directory path also can't be changed at the moment.

Could you provide a complete **minimal** reproducible repo?

**Reply by khrome83** [reply]
Yeah, I have the S3 settings setup and connected. 

This isn't the while `litefs.yml` but basically, LiteFs gets a director specified for FUSE, where the App writes too. The volume is mounted to another location that is specified in the `fly.toml` and should mirror the `data.dir` in the `litefs.yml`.

LiteFS runs in privileged mode, and acts as a supervisor and executes commands once it has connected to the cluster, including being promoted to primary. 

It also automatically disconnects when the app inside stops. So there are lots of benefits to this apporach.

```yml
# The fuse section describes settings for the FUSE file system. This file system
# is used as a thin layer between the SQLite client in your application and the
# storage on disk. It intercepts disk writes to determine transaction boundaries
# so that those transactions can be saved and shipped to replicas.
fuse:
  dir: "/pb_data"

# The data section describes settings for the internal LiteFS storage. We'll
# mount a volume to the data directory so it can be persisted across restarts.
# However, this data should not be accessed directly by the user application.
data:
  dir: "/var/lib/litefs"

# This section defines a list of commands to run after LiteFS has connected
# and sync'd with the cluster. You can run multiple commands but LiteFS expects
# the last command to be long-running (e.g. an application server). When the
# last command exits, LiteFS is shut down.
exec:
  - cmd: "pocketbase migrate up"
    if-candidate: true
  - cmd: "pocketbase serve --http 0.0.0.0:8055"
```

The `if-candidate: true` just ensures that the primary (writer) handles the migrations. I call it separate here, even though PocketBase runs it automatically, because I want the primary to do it, so when the other nodes call `pocketbase serve` and try to run migrations, they see it's already handled.

LiteFS handles the connection between `/var/lib/litefs` <-> `/pb_data` so it all happens under the hood.

It's possible this goes away when LiteFS introduces an alternative to FUSE (VFS i think). 

Let me see what I can do to make a smaller repo for evaluation. 

Ohh, to the other comment "Why do you need the extra go build tags?". 

IDK - I am still newer to Go, having used it off and on for the last 2 years as a hobby. I am still trying to bring it into my workplace 😈. This build statement i got from another example Dockerfile that fly.io had in a repo. Not sure the argument for them. 🤷 

If you know better, please suggest away =)
