### DISCUSSION TITLE
Can PocketBase host my app?

### DISCUSSION THREAD

**Discussion by VictorioBerra** [pocketbase/pocketbase#4213] [Q&A] [answered]
Can I save my files alongside PB and have PB serve my /dist/index.html along with its SSL cert?

**Comment by jonshipman** [comment]
Depends on what your app is. If you are hosting .html files, Pocketbase can serve those files if you rename the dist directory to pb_public.

**Reply by VictorioBerra** [reply]
Is that preferred over: https://pocketbase.io/docs/js-routing/#serving-static-files ? Or would that not work.

**Reply by VictorioBerra** [reply]
@jonshipman Not having much luck with that on docker:

## Docker Compose

```yaml
services:
  pocketbase:
    image: spectado/pocketbase:latest
    container_name: pocketbase
    restart: unless-stopped
    ports:
      - "8088:80"
    volumes:
      - ./pocketbase:/pb_data
      - ./pocketbase_public:/pb_public
```

## Container Console

![image](https://github.com/pocketbase/pocketbase/assets/2934507/b4041bde-4ecf-4bf0-b3ed-f944aede3a7b)

## Hit Static File

![image](https://github.com/pocketbase/pocketbase/assets/2934507/f75e99c5-159a-40e0-84a8-e598f95b6e13)

**Reply by VictorioBerra** [reply]
Maybe this is an issue with spectados container release?

**Reply by soukupl** [reply]
pb_public dir is not tested with docker image - it may be on wrong place inside the docker. I will look at it and will try to fix the builder script.

**Reply by ganigeorgiev** [reply]
@VictorioBerra `pb_public` works by default if the folder is mounted next to the executable. That is not the case with the image you are using - see the last [ENTRYPOINT instruction](https://hub.docker.com/layers/spectado/pocketbase/latest/images/sha256-ba3ee023aef5dbf3260f0cddeed56f69fb7bd1a73b25dd24ae9d4d00b0b4727b?context=explore&tab=vulnerabilities). usually when you want to specify a different location for the `pb_public` you can use the `--publicDir` flag but I'm not sure if this image allow support for this so instead what you can try is to mount your public directory next to the executable path, aka. replace the volume statement with something like:
```yaml
./pocketbase_public:/usr/local/bin/pb_public
```

Regarding `$apis.staticDirectoryHandler` - that is what `pb_public` use, it is just a convenient default route that comes with the prebuilt executable.

**Reply by VictorioBerra** [reply]
@ganigeorgiev using `/usr/local/bin/pb_public` worked!

**Reply by soukupl** [reply, marked as answer]
Hi,
I have just updated the dockerfile so the public directory would be mapped to /pb_public.  So the volumes for docker now had a one more (optional) entry.

```yml
volumes:
  - /path/to/data:/pb_data
  - /path/to/public:/pb_public
```

Change is in the **latest** tag and since version **0.20.7** (including).

**Reply by soukupl** [reply]
hello, dockerfile was updated, but you will have to tweak your docker settings as the PocketBase inside the docker expecting the public dir at path /pb_public (changed in the latest and 0.20.7+ version tags).
Sorry about this :)

```yml
volumes:
  - /path/to/data:/pb_data
  - /path/to/public:/pb_public
 ```

**Reply by soukupl** [reply]
BTW: you may need to manually delete already downloaded version to force re-download of fresh build...

**Reply by VictorioBerra** [reply]
@soukupl I think there is a bug with entrypoint.

My docker compose:

```yaml
services:
  pocketbase:
    image: spectado/pocketbase:latest
    container_name: pocketbase
    restart: unless-stopped
    ports:
      - "8088:80"
    volumes:
      - ./pocketbase/pb_data:/pb_data
      - ./pocketbase/pb_public:/pb_public
```

when I console into the container:

```
/ # ls -lah | grep pb_
drwxr-xr-x    4 root     root        4.0K Jan 23 15:54 pb_data
drwxr-xr-x    3 root     root        4.0K Jan 24 15:08 pb_data --publicDir=
drwxr-xr-x    2 root     root        4.0K Jan 22 18:32 pb_public
```

Notice that its actually creating a folder called "pb_data --publicDir="
