### DISCUSSION TITLE
pb_data not persisting for pocketbase go extension with dockerfile & docker-compose.yml

### DISCUSSION THREAD

**Discussion by noob8boi** [pocketbase/pocketbase#5180] [Q&A] [answered]
Dockerfile

```
FROM golang:1.22.4

WORKDIR /pb

COPY go.mod go.sum ./

RUN go mod download

COPY *.go ./

RUN CGO_ENABLED=0 GOOS=linux go build -o /pocketbase

CMD ["/pocketbase", "serve", "--http=0.0.0.0:8090"]
```

docker-compose.yml

```
services:
  pb:
    container_name: pb
    restart: unless-stopped
    build:
      context: ./pocketbase
      dockerfile: Dockerfile
    volumes:
      - ./pocketbase/pb_data:/pb/pb_data
    networks:
      - nginx-gateway
networks:
  nginx-gateway:
    name: nginx-gateway
    external: true
```

Project Structure [Image]
![image](https://github.com/pocketbase/pocketbase/assets/91360152/8f3d8a09-d86d-44a0-8ac2-9f9afd0eacb3)
