### DISCUSSION TITLE
Image URLs pointing to docker service instead of the server

### DISCUSSION THREAD

**Discussion by andrejbroncek** [pocketbase/pocketbase#5531] [Q&A]
Hey guys, I'm facing a bit of a problem with images served by pocketbase. I am running my pocketbase instance via docker, together with my node.js backend, sveltekit frontend, caddy etc. 

Everything works well, except for images. The URL pocketbase serves (for example for user avatar images) points to the pocketbase service, instead of the `localhost:8080` (I have port `8080` exposed in pocketbase dockerfile and opened via `compose.override` for local dev, domain reverse proxied to it on prod via `caddy`). The URL looks something like this: `http://pocketbase:8080/api/files/_pb_users_auth_/pyzdrob678ktx63/dgzgcl_nxyaejdy4_NtJWODpAMG.jpg?thumb=40x40` 

This is my docker compose file:

```
services:
  frontend:
    container_name: frontend
    build: ./frontend
    restart: always
    environment:
      - NODE_ENV=${NODE_ENV}
      - PB_URL=${PB_URL}
      - ORIGIN=${ORIGIN}
    depends_on:
      - pocketbase
      - caddy
    networks:
      - pocketnet
  
  backend:
    container_name: backend
    build: ./backend
    restart: always
    environment:
      - NODE_ENV=${NODE_ENV}
      - PB_URL=${PB_URL}
      - PB_EMAIL=${PB_EMAIL}
      - PB_PASSWORD=${PB_PASSWORD}
    depends_on:
      - pocketbase
      - caddy
    networks:
        - pocketnet

  pocketbase:
    build: ./pocketbase
    container_name: pocketbase
    restart: always
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pb_data:/pb_data
      - pb_public:/pb_public
      - pb_migrations:/pb_migrations
      - pb_hooks:/pb_hooks
    networks:
      - pocketnet

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - pocketbase
    networks:
      - pocketnet

volumes:
  pb_data:
  pb_public:
  pb_migrations:
  pb_hooks:
  caddy_data:
  caddy_config:

networks:
  pocketnet:
    driver: bridge
```
Can you tell pocketbase what URL to use as the host URL? Somehow, force it to replace the docker service URL with the actual server URL (be it localhost for local dev and specific domain for prod)? Thanks!
