### DISCUSSION TITLE
Pocketbase docker setup

### DISCUSSION THREAD

**Discussion by nelsonsilva94** [pocketbase/pocketbase#5547] [Q&A]
Hi all,

I have PocketBase running in a docker container.
I also have the `pb_data` and `pb_migrations` folder with my "Initial application data".

For now I am copying both folders to the container and when started, everything is as I want, I already have and admin and some default tables.

The problem I'm facing right now is, I want to persist the data added prior start, and for that I thought creating a volume would solve my needs, but doing so, when starting PocketBase container, I need to create an admin user and my database is "empty" (without my default tables).

I understand that, because when mounting the volume, the host folders are empty and overwrites the container folders.

Is there any way of having my default data when starting and also use volumes to persist data in the future?

Sorry if it is in the docs already, could not find a solution reading them.

Thanks in advance,

**Comment by ganigeorgiev** [comment]
There is nothing really PocketBase specific here but without details about your Dockerfile and what exactly do you mean by _"I also have the pb_data and pb_migrations folder with my Initial application data"_ it is difficult to understand what actually you are doing.

In general in order to have persistent PocketBase data when using Docker it is enough to mount your existing `pb_data` as volume. From your description that doesn't seem to be the case.

`pb_migrations` (and eventually `pb_hooks`) can be copied directly into the resulting container image (e.g. using the `COPY` instruction) because they are essentially part of you app code.

For an example Dockerfile you can refer to https://pocketbase.io/docs/going-to-production/#using-docker.

If the above doesn't help, please share your Dockerfile and how do you mount the volume.

**Reply by nelsonsilva94** [reply]
@ganigeorgiev Sorry for not being totally clear about my issue.

I agree that the problem is much more related to docker itself than PocketBase.

So, let me try to explain better what I am trying to do,

I ran a PocketBase container and created a admin user, added some custom tables and ended up with pb_data and pb_migrations folders.

I then created a new PocketBase docker image and copied the data and migrations inside the image, this is part of my Dockerfile:
```Docker
FROM alpine:latest

ARG PB_VERSION=0.20.0

RUN apk add --no-cache \
    doas \
    unzip \
    ca-certificates

RUN mkdir -p /pocketbase
WORKDIR /pocketbase

# download and unzip PocketBase
ADD https://github.com/pocketbase/pocketbase/releases/download/v${PB_VERSION}/pocketbase_${PB_VERSION}_linux_amd64.zip /tmp/pocketbase.zip
RUN unzip /tmp/pocketbase.zip -d /pocketbase/

ADD ./deployment-cobalt/pocketbase/pb_data /pocketbase/pb_data
ADD ./deployment-cobalt/pocketbase/pb_migrations /pocketbase/pb_migrations
```

Then I started PocketBase with docker-compose and my service is the following:
```yaml
pocketbase:
    image: <private_registry>/ip-mv-pocketbase/pocketbase
    container_name: pocketbase
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    labels:
      logging: "promtail"
      logging_jobname: "pocketbase-logs"
    restart: unless-stopped
    command: ["./pocketbase", "serve", "--http=0.0.0.0:${POCKETBASE_PORT}"]
    networks:
      - gateway
    ports:
      - "${POCKETBASE_PORT}:${POCKETBASE_PORT}"
    volumes:
      - ./ipmv/pocketbase/data:/pocketbase/pb_data
    healthcheck:
      #optional (recommended) since v0.10.0
      test: wget --no-verbose --tries=3 --spider http://${MACHINE_IP}:${POCKETBASE_PORT}/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
```

When trying to access PocketBase, it asks for admin user creation.

However, if I do not mount the volume, it works as expected, I login with my previous admin user and all my custom data is there.

I want to persist data and I sure I am missing a small detail.
