### DISCUSSION TITLE
Github Action / Build / Deploy as a Framework in Docker

### DISCUSSION THREAD

**Discussion by WebPirat** [pocketbase/pocketbase#5581] [Q&A]
Hello,

When using Pocketbase as a Framework someone tried to use it in a pipeline ?
cant figure out the right way to use it with hooks and migration and save way to deploy the changes, would be nice if someone got advice or rough idea i could look into.

Thanks!

**Comment by pnmcosta** [comment]
Yes, definitely possible, I do almost daily to a Shopify app in production. Considering that:

> New migrations are applied automatically on serve. 

See https://pocketbase.io/docs/go-migrations/ for more info.

I don't think hooks or migrations to be issue as when the container first runs migrations will always apply, and hooks will always work (unless I'm misunderstanding what you're referring to) but rather how/where you're deploying to that matters most IMO.

In my case I'm deploying to Fly.io, I use docker's own actions to build the image, then push it to fly's registry (but you can use your own like gh's) and use fly's cli to deploy in separate jobs all on the same GitHub workflow.

Here's a truncated example of the jobs, you probably won't be able to copy paste directly, but should help you get going:

```
  image:
    name: build image
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.build.outputs.imageid }}
    permissions:
      actions: write
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          provenance: false
          outputs: type=docker,dest=/tmp/image.tar
          cache-from: type=gha,scope=ci,ignore-error=true
          cache-to: type=gha,scope=ci,ignore-error=true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          tags: |
            registry.fly.io/${{ vars.APP_NAME }}:${{ needs.changes.outputs.tag }}
            registry.fly.io/${{ vars.APP_NAME }}:latest

      - run: |
          echo "## Image tags" >> $GITHUB_STEP_SUMMARY
          echo "- ${{ steps.build.outputs.imageid }}" >> $GITHUB_STEP_SUMMARY
          echo "- registry.fly.io/${{ vars.APP_NAME }}:${{ needs.changes.outputs.tag }}" >> $GITHUB_STEP_SUMMARY
          echo "- registry.fly.io/${{ vars.APP_NAME }}:latest" >> $GITHUB_STEP_SUMMARY

      - uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: "image-${{ github.sha }}"
          path: /tmp/image.tar

  push:
    runs-on: ubuntu-latest
    name: push to fly
    outputs:
      image: ${{ steps.image.outputs.image }}
    needs:
      - image
    steps:
      - uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          version: 0.3.2

      - run: flyctl auth docker
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: "Download image"
        uses: actions/download-artifact@v4
        with:
          name: "image-${{ github.sha }}"
          path: /tmp

      - name: "Load image"
        run: docker load --input /tmp/image.tar

      - name: "Generate image name"
        id: image
        run: echo "image=registry.fly.io/${{ vars.APP_NAME }}:${{ github.sha }}" >> $GITHUB_OUTPUT

      - name: "Tag image"
        run: docker tag ${{ needs.image.outputs.image }} ${{ steps.image.outputs.image }}

      - name: "Push image"
        run: docker push ${{ steps.image.outputs.image }}

  deploy:
    runs-on: ubuntu-latest
    name: fly deploy
    needs: push
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          version: 0.3.2

      - name: "Deploy app"
        run: flyctl deploy
          -a ${{ vars.APP_NAME }}
          --remote-only
          --image-label ${{ needs.changes.outputs.tag }}
          --image ${{ needs.push.outputs.image }}
          -e APP_NAME=${{ vars.APP_NAME }}
          --ha=false
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
```

And here's a summary of a successful run with all the other jobs I also have for a visualization guideline

![image](https://github.com/user-attachments/assets/2334ab0b-e600-4f3b-baea-a391dbd0081d)
