### DISCUSSION TITLE
App Settings can't be saved (>v.0.20)

### DISCUSSION THREAD

**Discussion by OskarPetersilie** [pocketbase/pocketbase#5752] [Q&A] [answered]
Hey i am using pocketbase for several applications i create.

The newest app sends emails via smtp. While configuring smtp in my poketbase i stumbled upon 400 requests without any data while trying to update the app setting.

I tested in v0.21 and v0.22. It does not work and i cant find any error messages.

Works with v.0.20

my docker-compos.yml which i use to manage the pb

```
services:
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:0.20 #change to 0.22 or 0.21 for tests
    container_name: gbl-pocketbase
    restart: unless-stopped
    ports:
      - "8103:8090"
    volumes:
      - ./db/pb_data:/pb_data
      - ./db/pb_public:/pb_public
      - ./db/pb_migration:/pb_migration
      - ./db/pb_hooks:/pb_hooks
    healthcheck: #optional (recommended) since v0.10.0
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
  ```
   

 Application and Mail Settings tabs are not working.
   
   ```

   fetch("https://myUrl/myAppDomainPath/api/settings", {
  "headers": {
    "accept": "*/*",
    "accept-language": "en-US",
    "authorization": "auth",
    "cache-control": "no-cache",
    "content-type": "application/json",
    "pragma": "no-cache",
    "sec-ch-ua": "\"Chromium\";v=\"130\", \"Google Chrome\";v=\"130\", \"Not?A_Brand\";v=\"99\"",
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": "\"Windows\"",
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "same-origin",
    "Referer": "https://myurl/myPath/_/",
    "Referrer-Policy": "strict-origin-when-cross-origin"
  },
  "body": "{\"meta\":{\"appName\":\"Acmed\",\"appUrl\":\"http://localhost:8090\",\"hideControls\":false,\"senderName\":\"Support\",\"senderAddress\":\"support@example.com\",\"verificationTemplate\":{\"body\":\"<p>Hello,</p>\\n<p>Thank you for joining us at {APP_NAME}.</p>\\n<p>Click on the button below to verify your email address.</p>\\n<p>\\n  <a class=\\\"btn\\\" href=\\\"{ACTION_URL}\\\" target=\\\"_blank\\\" rel=\\\"noopener\\\">Verify</a>\\n</p>\\n<p>\\n  Thanks,<br/>\\n  {APP_NAME} team\\n</p>\",\"subject\":\"Verify your {APP_NAME} email\",\"actionUrl\":\"{APP_URL}/_/#/auth/confirm-verification/{TOKEN}\",\"hidden\":false},\"resetPasswordTemplate\":{\"body\":\"<p>Hello,</p>\\n<p>Click on the button below to reset your password.</p>\\n<p>\\n  <a class=\\\"btn\\\" href=\\\"{ACTION_URL}\\\" target=\\\"_blank\\\" rel=\\\"noopener\\\">Reset password</a>\\n</p>\\n<p><i>If you didn't ask to reset your password, you can ignore this email.</i></p>\\n<p>\\n  Thanks,<br/>\\n  {APP_NAME} team\\n</p>\",\"subject\":\"Reset your {APP_NAME} password\",\"actionUrl\":\"{APP_URL}/_/#/auth/confirm-password-reset/{TOKEN}\",\"hidden\":false},\"confirmEmailChangeTemplate\":{\"body\":\"<p>Hello,</p>\\n<p>Click on the button below to confirm your new email address.</p>\\n<p>\\n  <a class=\\\"btn\\\" href=\\\"{ACTION_URL}\\\" target=\\\"_blank\\\" rel=\\\"noopener\\\">Confirm new email</a>\\n</p>\\n<p><i>If you didn't ask to change your email address, you can ignore this email.</i></p>\\n<p>\\n  Thanks,<br/>\\n  {APP_NAME} team\\n</p>\",\"subject\":\"Confirm your {APP_NAME} new email address\",\"actionUrl\":\"{APP_URL}/_/#/auth/confirm-email-change/{TOKEN}\",\"hidden\":false}}}",
  "method": "PATCH"
});
```

Response

```
{"code":400,"message":"An error occurred while submitting the form.","data":{}}

`

**Comment by ganigeorgiev** [comment]
I don't think your issue is PocketBase related (_we also have [integration tests](https://github.com/pocketbase/pocketbase/blob/0b304351830a6b8d1254f9ed69f9991c0247243b/apis/settings_test.go#L103) that verify the settings update action is working correctly_) and it is most likely one of:
- something is wrong with your Docker setup (I'm not familiar with the Docker image you are using and if your problem happens only when using it, then you should contact the respective author)
- the client request body is invalid (note also that the settings requires Admin `Authorization:TOKEN` header)
- there is a conflicting custom hooks code

The easiest way to rule out PocketBase issue is to send request to PocketBase directly by creating a static `pb_public/index.html` file:

```html
<!DOCTYPE html />
<html>
<head>
    <meta charset="utf-8" />
    <title>Test</title>
</head>
<body>
    <script type="module">
        import PocketBase from "https://cdn.jsdelivr.net/gh/pocketbase/js-sdk@master/dist/pocketbase.es.mjs"

        const pb = new PocketBase("http://127.0.0.1:8090");

        await pb.admins.authWithPassword("test@example.com", "1234567890")

        await pb.settings.update({
            meta: {
                appName: "Acme2"
            }
        })
    </script>
</body>
</html>
```
Open your browser, navigate to `http://127.0.0.1:8090` and check the Inspect tool console and network tab.

In general, you can find more detailed errors by starting the executable with `--dev` and/or search for the failed request in the UI > Logs section.

**Reply by OskarPetersilie** [reply]
Hey thanks for the fast answer. 
Didnt found the integration tests. then i wouldn't have created the issue.

The Authorisation header gets send i just removed the token. 
I will remove all hooks and check again.

also thanks for the --dev hint will check that out for further debugging.

**Reply by OskarPetersilie** [reply]
Okay i just retestet and I cant reproduce the error local with docker compose on the versions i mentioned.

Maybe i add some Auth issues/overlaps with other pb instances.

Still not able to update on my live Pocketbase instances with are behind a ngin reverse proxy.

I also host all those poketbases behind a nginx reverse proxy to a domainPath.

myUrl.dev/app1/_ would be my pocketbase instance. Could it be that theres some hiccup with this approach and the request gets cancelled?

**Reply by OskarPetersilie** [reply]
Okay i found some error message

{
  "id": "g61w1n1kff35ttd",
  "created": "2024-10-30 13:55:12.249Z",
  "updated": "2024-10-30 13:55:12.249Z",
  "data": {
    "auth": "admin",
    "details": "crypto/aes: invalid key size 7",
    "error": "An error occurred while submitting the form.",
    "execTime": 1.067746,
    "method": "PATCH",
    "referer": "https://myurl/mypath/_/",
    "remoteIp": "172.23.0.1",
    "status": 400,
    "type": "request",
    "url": "/api/settings",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36",
    "userIp": "myip"
  },
  "message": "PATCH /api/settings",
  "level": 8
}

**Reply by ganigeorgiev** [reply]
I really don't know how to help you.

Based on the error message it seems that maybe you have/had settings encryption enabled?

The image and the error message is very similar to https://github.com/pocketbase/pocketbase/issues/1902.

**Reply by OskarPetersilie** [reply, marked as answer]
Hey Fixed it, the problem was a inalid encryption key length. (32 encryption key length requried)

Docker Encryption example: [Link to example](https://github.com/muchobien/pocketbase-docker?tab=readme-ov-file#docker-compose-recommended)

And here the correspondig Pocketbase Docu: https://pocketbase.io/docs/going-to-production/#enable-settings-encryption

Pocketbase docu mentiones a 32 char long key. 

Problem didnt show since (4 projects due to the fact i dont use settings, emails that often)

Besides that thanks for being so patiened and helping everyone. Pocketbase is such a mighty framework i love to work with it and it allows me to create WebApps blazinly fast. Insane work. Much love.

Fixed docker-compose.yml
```
version: "3.7"
services:
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: pocketbase
    restart: unless-stopped
    command:
      - --encryptionEnv #optional
      - ENCRYPTION #optional
    environment:
      ENCRYPTION: example #optional MAKE SURE 32 char long if used
    ports:
      - "8090:8090"
    volumes:
      - /path/to/data:/pb_data
      - /path/to/public:/pb_public #optional
      - /path/to/hooks:/pb_hooks #optional
    healthcheck: #optional (recommended) since v0.10.0
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
```
