### DISCUSSION TITLE
is cloudflare tunnels supported?

### DISCUSSION THREAD

**Discussion by modpotato** [pocketbase/pocketbase#6391] [Q&A] [answered]
havent seen anything about cf tunnels (as the topic) in other issues but if i want to use https through cloudflare, how would i go about doing that?
http doesnt work because of SSL_ERROR_NO_CYPHER_OVERLAP i believe, but i havent re tested that yet
so i thought about trying to skip tls verify on the cloudflare tunnel and just see if i can pass through and make pocketbase think it was directly at the domain as theoretically that would work, then pb would get its certificate and cloudflare/the browser would be happy:
root@localhost:~/pb# /root/pb/pocketbase serve --https pb.archive.localhost.top:443 
Error: listen tcp 104.21.96.1:443: bind: cannot assign requested address

so how would i go about getting this to work? or is there no way to make it work as it stands?

**Comment by latchk3y** [comment, marked as answer]
Yes, this is possible.

Rather than binding the tunnel to PB directly, you would do your normal `./pocketbase serve`, and then you'd use the cloudflared daemon for whatever system you're running on, and create a tunnel via:
```bash
cloudflared tunnel create <TUNNEL_NAME_HERE>
```

Then, you want to edit the config file (which on Linux is usually located at `~/.cloudflared/config.yaml`) with the following:
```yaml
tunnel: <TUNNEL_UUID>
credentials-file: /path/to/credentials/file.json

ingress:
  - hostname: yourdomain.com
    service: http://127.0.0.1:8090
  - service: http_status:404
  ```

Replace:
- `<TUNNEL_UUID>` with the UUID of your tunnel.
- `yourdomain.com` with the subdomain you want to use for PB.
- `/path/to/credentials/file.json` with the path to the credentials file generated during tunnel creation.

And then finally, you would route traffic as normal:
```bash
cloudflared tunnel route dns <TUNNEL_UUID> yourdomain.com 
cloudflared tunnel run <TUNNEL_NAME>
```

**Reply by modpotato** [reply]
funny enough i was doing this, but i wanted to keep local access so i was binding to the local ip. is there a way i could retain local access without having to forward a port over ssh or something like that?

**Reply by latchk3y** [reply]
I'm not sure I understand the question.

**Reply by modpotato** [reply]
pocketbase is running on a LXC in my rack server, not on my local machine, so i cant access localhost
and cloudflare has 100mb upload limits, and in general id like local access to pb

**Reply by latchk3y** [reply]
Ah, in that case, you should be able to bind PB to a local IP address like so:
```bash
./pocketbase serve --http=192.168.1.100:8090
```

And then you just edit your YAML file to have that as the service:
```yaml
ingress:
  - hostname: yourdomain.com
    service: http://192.168.1.100:8090
  - service: http_status:404
```

This should allow you to access it without using port forwarding or SSH tunneling.
