### DISCUSSION TITLE
Have docker image?

### DISCUSSION THREAD

**Discussion by chaochaokeji** [pocketbase/pocketbase#64] [Q&A]
i want to use docker install pocketbase!

**Comment by ganigeorgiev** [comment]
Currently there is no official Docker image, but you may not need it because PocketBase is portable and doesn't require installation or have any external dependency. For most of the cases, it should be enough to just download the binary for your platform from the [releases page](https://github.com/pocketbase/pocketbase/releases) and execute it on the server.

But I will consider adding official Docker support when we reach a little more stable version since this seems to be a common request.

**Reply by chaochaokeji** [reply]
thank you!

**Comment by KROSF** [comment]
@chaochaokeji here i created a docker image based on pocketbase releases https://github.com/muchobien/pocketbase-docker

**Reply by chaochaokeji** [reply]
thank you!

**Comment by zdeneksvarc** [comment]
You can try this pretty easy `docker-compose.yml` based on https://github.com/muchobien/pocketbase-docker without encrypted db.

```
version: '3.7'
services:
  pocketbase:
    container_name: pocketbase
    image: ghcr.io/muchobien/pocketbase:0.2.7
    restart: always
    command:
      - pocketbase
      - serve
      - --http
      - 0.0.0.0:8090
      - --dir
      - /data
    ports:
      - "8090:8090"
    volumes:
      - ./pocketbase:/data
```
