### DISCUSSION TITLE
How to migrate pb_data from bind mount to named volume?

### DISCUSSION THREAD

**Discussion by nicetomytyuk** [pocketbase/pocketbase#6539] [Q&A]
I have a pocketbase solution hosted with docker compose, the solution is using bind mount and has a folder with `pb_data` and `pb_migrations`, in the new project I use named volume instead for `pb_data` and I would like to migrate the data from the old project to the new one.

Do do it I copy the `pb_data` from the old project and create a named volume with it, then I run my new docker-compose.yml that uses named volume instead.

The issue is in migration files as when I try to run the solution I get errors like:

`Failed to apply migration 1738754301_updated_devices.js:`

My Dockerfile looks like this:

```
FROM alpine:latest as builder

ARG PB_VERSION=0.25.4

# Install necessary packages
RUN apk add --no-cache \
    unzip \
    ca-certificates \
    npm

# Download and unzip PocketBase
ADD https://github.com/pocketbase/pocketbase/releases/download/v${PB_VERSION}/pocketbase_${PB_VERSION}_linux_amd64.zip /tmp/pb.zip
RUN unzip /tmp/pb.zip -d /pb/

# Copy and build pb_hooks
COPY ./pb_hooks /pb/pb_hooks
WORKDIR /pb/pb_hooks/hooks-ts
RUN npm ci
RUN npm run build
WORKDIR /pb/pb_hooks
RUN rm -rf ./hooks-ts

FROM alpine:latest

# Copy the PocketBase binary and pb_hooks from the builder
COPY --from=builder /pb/ /pb/

# Copy the pb_migrations directory
COPY ./pb_migrations /pb/pb_migrations

# Copy the pb_template directory
COPY ./pb_template /pb/pb_template

# Copy the entrypoint script
COPY ./entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# Debug: Verify that the entrypoint script exists and is executable
RUN ls -l /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]

# Expose the PocketBase port
EXPOSE ${PB_PORT}

# Start PocketBase
CMD /pb/pocketbase serve --http=0.0.0.0:${PB_PORT}
```

The entrypoint.sh:

```
#!/bin/sh

# Check if pb_data is empty
if [ -z "$(ls -A /pb/pb_data)" ]; then
   echo "Initializing pb_data from pb_template..."
   cp -r /pb/pb_template/* /pb/pb_data/
fi

# Execute the main command
exec "$@"
```

In docket-compose.yml:
```
pocketbase:
    image: company/signage-pocketbase:latest
    container_name: signage-pocketbase
    restart: always
    volumes:
      - 'pb_data:/pb/pb_data'
    env_file:
      - .env
    expose:
      - '${PB_PORT}'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PB_PORT}/api/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - main
```
