### DISCUSSION TITLE
PocketBase as a framework, docker-compose, nginx example

### DISCUSSION THREAD

**Discussion by apikee** [pocketbase/pocketbase#942] [Show and tell]
Hope this can help someone:

Dockerfile
```
FROM golang:1.18 AS builder

RUN mkdir /app
ADD . /app
WORKDIR /app

RUN CGO_ENABLED=0 GOOS=linux go build -o my_app cmd/server/main.go

FROM alpine:latest AS production
COPY --from=builder /app .
CMD ["./my_app", "serve", "--http", "my_app:8090"]
```

docker-compose.yml (not sure if the expose is needed)
```
version: "3.8"

services:
  my_app:
    build: .
    container_name: my_app
    depends_on:
      - nginx
    ports:
      - "8090:8090"
    volumes:
      - my_app:/pb_data
    env_file:
      - .env.prod
    expose:
      - "8090"
    networks:
      - network

  nginx:
    image: "nginx"
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    expose:
      - "80"
    networks:
      - network

volumes:
  my_app:

networks:
  network:
    driver: bridge
```

nginx.conf
```
worker_processes  1;

events {
    worker_connections  1024;
}

http {
   
  #  ...default setup

    server {
        listen 80;
        server_name my_app.com;

        location / {
            proxy_set_header Connection '';
            proxy_http_version 1.1;
            proxy_read_timeout 360s;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_pass http://my_app:8090;
        }
    }

    # ...default setup
}

```
