### ISSUE TITLE
Tried to change the App Name in the admin settings.

### ISSUE THREAD

**Issue by mez** [pocketbase/pocketbase#1902]
Got the following error.

```
api/settings

{
  "code": 401,
  "message": "The request requires valid admin authorization token to be set.",
  "data": {
    
  }
}
```

**Comment by ganigeorgiev** [comment]
I'm not able to reproduce it (_there also automated tests that verify the correct behavior_).

Make sure that your request has `Authorization: ADMIN_TOKEN` header.

If you are testing on the live demo (https://pocketbase.io/demo/), the above error could occur during db reset.

If the above doesn't help, please provide a little more details about your setup and reproducible steps, and I'll investigate it.

**Comment by mez** [comment]
@ganigeorgiev,

I did a little experiment. Two setups, one worked the other didn't.

1. ./pocketbase serve from terminal (**works**)
2. pocketbase in a docker container, with only volume mount for the "pb_data" directory. (**Not Working**)

Used the docker-compose file below

```
version: '3.7'

volumes:
  pocketbase:
    external: true

services:
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: pocketbase
    restart: unless-stopped
    command:
      - --encryptionEnv #optional
      - ENCRYPTION #optional
    environment:
      ENCRYPTION: example #optional
    ports:
      - "8090:8090"
    volumes:
      - pocketbase:/pb_data
    healthcheck: #optional (recommended) since v0.10.0
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
```
