### ISSUE TITLE
Failed to create backup in Docker

### ISSUE THREAD

**Issue by Aragur** [pocketbase/pocketbase#3089]
The Backup functionality isn't working on my instance.
Using the latest version of Pocketbase and Docker.

`--debug`-Log shows the following:
```
blob (key "pb_backup_20230808092633.zip") (code=Unknown): rename /tmp/pb_backup_20230808092633.zip.17795e46db5a7b21.tmp /pb_data/backups/pb_backup_20230808092633.zip: invalid cross-device link
```

**Comment by ganigeorgiev** [comment]
I think this was fixed in v0.16.3+. What version of PocketBase do you use?

**Comment by Aragur** [comment]
I'm using 0.17.2

**Comment by ganigeorgiev** [comment]
Hm, what was fixed before was the restore functionality (see https://github.com/pocketbase/pocketbase/issues/2519) but I forgot to check the backup.

I'll test it sometime later today and will try to submit a fix.

**Comment by ganigeorgiev** [comment]
Should be fixed in [PocketBase v0.17.3](https://github.com/pocketbase/pocketbase/releases/tag/v0.17.3).

If the above doesn't resolve your issue please provide more details about your Docker setup and I'll try to investigate it further.

**Comment by Aragur** [comment]
@ganigeorgiev still the same issue after upgrading to v0.17.3.

### My Docker-Compose file
```yaml
services:
  example-server:
    restart: always
    image: private-image
    command: ["/server", "serve", "--http=0.0.0.0:8090", "--debug"]
    volumes:
      - ./data:/pb_data:rw
```

### My Dockerfile
```Dockerfile
## Build
FROM golang:1.20-buster as build

WORKDIR /app

COPY server/go.mod ./
COPY server/go.sum ./
COPY server/pkg ./pkg
RUN go mod download

COPY server/*.go ./

RUN CGO_ENABLED=1 go build -o /server

## Deploy
FROM gcr.io/distroless/base-debian10

WORKDIR /

COPY --from=build /server /server
COPY webapp/dist /webapp

EXPOSE 8090

ENTRYPOINT ["/server", "serve", "--http=0.0.0.0:8090"]
```
