### ISSUE TITLE
creates an Error when coming over reverse proxy

### ISSUE THREAD

**Issue by swoop124** [pocketbase/pocketbase#3218]
I downloaded pocketbase-binary and started it like this: `./pocketbase serve --http 0.0.0.0:8090`. 
It is reachable over direkt IP, than i created a User. When i try to reach `https://komo.domain.tld` over my reverse proxy and try to log in with the user and password i created earlier, then pocketbase gives this error:
![grafik](https://github.com/pocketbase/pocketbase/assets/75502165/152cf532-7e3a-4ea8-bc52-de8cb9e49ea1)

**Comment by ganigeorgiev** [comment]
I guess this is related to https://github.com/pocketbase/pocketbase/discussions/3170#discussioncomment-6850369.

When you say _"i created a User"_, do you mean a PocketBase admin account?

Please note that PocketBase admins and users are 2 different entities, each with their own JWT secrets, meaning that using a user token to authenticate as admin will not work.

If the proxy is causing an issue, then double check that the `Authorization` header is properly proxied to the PocketBase server. This is the only requirement the authentication to work.

**Comment by swoop124** [comment]
hello,

yes i think this thread is realted and yes i mean an admin user.
In my opinion, there is only pocketbase that can be the problem, because as I first encountered that problem, it was after an update, about 5 or 6 Month ago. Til than it worked fine.
I am using [UpSnap](https://github.com/seriousm4x/UpSnap) it is using pocketbase as backend.
The creator has mentioned, that i should post the error here.
I also created a over at UpSnap: [Issue at UpSnap](https://github.com/seriousm4x/UpSnap/issues/65)

**Comment by ganigeorgiev** [comment]
Please understand I'm not able to reproduce it. We also have automated tests that verify the correct behavior.

There is something wrong with your setup, but without clear reproducible and **minimal** steps I don't think I can help you.

**Comment by swoop124** [comment]
hello, 
i understand but somewhere has to be a flaw.

my setup:
1. I created a Proxmox VM for my Nginx Proxy Manager. The Proxmox and VM is located in DMZ.
    ![262272920-46accaa0-e80a-46fd-95b3-2127011143a5](https://github.com/pocketbase/pocketbase/assets/75502165/4bea8b7c-1db9-4d05-8b3f-7eed0ef8e378)
2. Than i installed Debian 11 and docker, as described in docker-docs. After the descovery of this problem, i upgradet it to Debian bookworm (12).
3. Then i created the NPM-Dockercontainer via this docker-compose.yml:
```
version: "3"
services:
  app:
    environment:
      - DB_MYSQL_HOST=db
      - DB_MYSQL_PORT=3306
      - DB_MYSQL_USER=npmuser
      - DB_MYSQL_PASSWORD=xxxxxxxxxx
      - DB_MYSQL_NAME=npm
    image: jc21/nginx-proxy-manager:latest
    # image: jc21/nginx-proxy-manager:github-pr-2599
    networks:
      npm_test:
        ipv6_address: xxx:xxxx:xxxx:xxxx:xxxx:ac11:1001
    ports:
      - 443:443/tcp
      - 80:80/tcp
      - 81:81/tcp
    restart: always
    volumes:
      - /opt/npm/letsencrypt:/etc/letsencrypt:rw
      - /opt/npm/data:/data:rw
  db:
    environment:
      - MYSQL_ROOT_PASSWORD=xxxxx
      - MYSQL_DATABASE=xxxxxxxx
      - MYSQL_USER=npmuser
      - MYSQL_PASSWORD=xxxxxxxx
    image: jc21/mariadb-aria:latest
    networks:
      - npm_test
    restart: always
    volumes:
      - /opt/npm/data/mysql:/var/lib/mysql:rw

networks:
  npm_test:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: xxx:xxxx:xxxx:xxxx::/64
```
4. Then i added some reverse proxy entrys such as for Upsnap:
![262275767-f1336707-c1c9-4e12-9605-69654983d1a8](https://github.com/pocketbase/pocketbase/assets/75502165/2b113fe6-3a6c-4ecc-a684-753039f21dd7)
 After many tests i endet up with this settings:
 
![262275767-f1336707-c1c9-4e12-9605-69654983d1a8](https://github.com/pocketbase/pocketbase/assets/75502165/22ee1672-912d-4f21-afb9-c1ab0721d656)
![262276107-e9568553-a8be-4669-9c3a-7868742ef8fb](https://github.com/pocketbase/pocketbase/assets/75502165/a2bbf163-84a6-4eb0-b1e8-7e6cc86989e4)
![262276295-ae45f29f-3910-40a0-b9f3-0a2f80853e76](https://github.com/pocketbase/pocketbase/assets/75502165/9b056970-563b-42b2-a4f4-7bd9bf568206)
5. Then i created a LXC (Debian 11) on a Proxmox Server that is located in LAN and installed Docker als described in the docker-docs.
![262277074-16d87a9c-0005-4517-af06-750b9798f033](https://github.com/pocketbase/pocketbase/assets/75502165/a496bb68-f2da-4b7a-bf1a-aa6e1636afe9)
6. In this LXC are running several docker-container. One of them is Upsnap. I used this docker-compose.yml```

version: "3"
services:
  upsnap:
    container_name: upsnap
    image: ghcr.io/seriousm4x/upsnap:3
    #image: ghcr.io/seriousm4x/upsnap:3.1.1
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./data:/app/pb_data
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 1m
      timeout: 10s
      retries: 3
    environment:
      - TZ=Europe/Berlin # Set container timezone for cron schedules
      - UPSNAP_INTERVAL=@every 10s # Sets the interval in which the devices are pinged
    #   - UPSNAP_SCAN_RANGE=192.168.1.0/24 # Scan range is used for device discovery on local network
    #   - UPSNAP_WEBSITE_TITLE=Custom name # Custom website title
    # command: ["./upsnap", "serve", "--http", "0.0.0.0:8090"] # Uncomment this if you want to change the port for example
```
What i have done so far:
I updated all participated linux and docker.
I changed hosts for docker and installed all requirements and docker-containers involved. I used lxc for these test, but no difference.
