### ISSUE TITLE
Live Reload

### ISSUE THREAD

**Issue by nepalsaurav** [pocketbase/pocketbase#4060]
Is there an option for live reload in PocketBase to view changes instantly while coding? If not, any plans to implement it?

**Comment by ganigeorgiev** [comment]
No, at least not of the box and there are no plans for that.

PocketBase is distributed as a regular Go library so you can combine it with external solutions like [air](https://github.com/cosmtrek/air) or similar.

**Comment by harendra21** [comment]
You can use `air` for live reload

**Make sure to mode `pb_data` inside the `tmp` folder**

.air.toml
```toml
root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
# ["serve", "--http=127.0.0.1:8080"]
args_bin = ["serve", "--http=127.0.0.1:8080"]
bin = "./tmp/main"
cmd = "go build -o ./tmp/main ."
delay = 0
exclude_dir = [
    "assets",
    "tmp",
    "vendor",
    "testdata",
    "pb_data",
    "pb_migrations",
]
exclude_file = []
exclude_regex = ["_test.go"]
exclude_unchanged = false
follow_symlink = false
full_bin = ""
include_dir = []
include_ext = ["go", "tpl", "tmpl", "html"]
include_file = []
kill_delay = "0s"
log = "build-errors.log"
poll = false
poll_interval = 0
rerun = false
rerun_delay = 500
send_interrupt = false
stop_on_root = false

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
main_only = false
time = false

[misc]
clean_on_exit = false

[screen]
clear_on_rebuild = false
keep_scroll = true
```
