### ISSUE TITLE
Feature Request: Dark Mode

### ISSUE THREAD

**Issue by MrDogeBro** [pocketbase/pocketbase#407]
Just a relatively simple feature request. It would be nice if there was a UI option to enable a dark mode since the light mode can be a bit much sometimes. That's all. Just a dark mode for the eyeballs. Thanks!

**Comment by ganigeorgiev** [comment]
I'll add the request to the roadmap, but it will be a low priority for now.

PocketBase is still in its very early development stage and different color scheme(s) will be hard to maintain while still doing changes in the UI. We use CSS variables, but modifying the colors usually is not enough and there will be always some components that will need special adjustment to make them visually more appealing and consistent.

**Comment by innovatorved** [comment]
If you dont have any problem i would love to build the Dark mode feature

**Comment by ganigeorgiev** [comment]
@innovatorved Thank you, but my advice for now would be to wait because there are expected to be a lot of changes to the Admin UI related to https://github.com/pocketbase/pocketbase/issues/376.

In general, as I mentioned, the project is still in its early development stage and it will be better to first reach a little more stable version before adding a Dark mode since it will be hard to maintain both when adding new features.

**Comment by innovatorved** [comment]
> @innovatorved Thank you, but my advice for now would be to wait because there are expected to be a lot of changes to the Admin UI related to #376.
> 
> In general, as I mentioned, the project is still in its early development stage and it will be better to first reach a little more stable version before adding a Dark mode since it will be hard to maintain both versions when adding new features.

@ganigeorgiev Sure

**Comment by tigawanna** [comment]
the admin dashboard works really well with the chrome dark mode flag enabled

**Comment by brodriguez-eb** [comment]
Open google console and paste this code:
```js
document.children[0].style.filter = "invert(1)"
```

**Comment by brewhousedigital** [comment]
> Open google console and paste this code:
> 
> ```js
> document.children[0].style.filter = "invert(1)"
> ```

I think this might be easier in the Svelte UI

```css
html {
    filter: invert(1);
}
`

**Comment by eslym** [comment]
> > Open google console and paste this code:
> > ```js
> > document.children[0].style.filter = "invert(1)"
> > ```
> 
> I think this might be easier in the Svelte UI
> 
> ```css
> html {
>     filter: invert(1);
> }
> ```

😂 add more

```css
html {
    filter: invert(1);
}
img {
    filter: invert(1); // invert img back to normal
}
```

**Comment by PeterAlfonsLoch** [comment]
> Open google console and paste this code:
> 
> ```js
> document.children[0].style.filter = "invert(1)"
> ```
> 
> or even a more fancier (complete) solution:
> 
> ```js
> const style = document.createElement('style');
> style.type = 'text/css'
> const styleCss = 'html { filter: invert(1); } img, g-emoji { filter: invert(1) }' ;
> style.styleSheet ? (style.styleSheet.cssText = styleCss) : style.appendChild(document.createTextNode(styleCss));
> document.getElementsByTagName('head')[0].appendChild(style);
> ```

I used it with the chrome plugin "User Javascript and CSS" works very well

**Comment by sergio9929** [comment]
I made this dark theme using Nuxt's color scheme:
![127 0 0 1_8090___(MacBook Air 2)](https://github.com/pocketbase/pocketbase/assets/29752861/d45456dc-0961-480d-83e2-7ae69fdaa537)
![127 0 0 1_8090___(MacBook Air 2) (1)](https://github.com/pocketbase/pocketbase/assets/29752861/16264b0f-e90c-4a91-b746-6e8c0dc20719)
![127 0 0 1_8090___(MacBook Air 2) (2)](https://github.com/pocketbase/pocketbase/assets/29752861/58883b5e-b1ed-46d6-abc6-7f1559543859)
![127 0 0 1_8090___(MacBook Air 2) (3)](https://github.com/pocketbase/pocketbase/assets/29752861/7ebe0a1b-e8b0-4d5d-b291-05e1705cd056)


## Installation
To use this theme in your browser you need to:
1. install a chrome extension like [Stylus](https://chrome.google.com/webstore/detail/stylus/clngdbkpkpeebahjckkjfobafhncgmne) or [Stylish](https://chrome.google.com/webstore/detail/stylish-custom-themes-for/fjnbnpbmkenffdnngjfgmeleoegfcffe).
2. Create a new userstyle pointing to the url where you use Pocketbase
3. Paste the css
4. Save and activate

You can change the accent color with this custom property:
```css
--primaryColor: #00dc82;
```

Here is the css:
```css
:root {
    --baseFontFamily: "Source Sans Pro", sans-serif, emoji;
    --monospaceFontFamily: "Ubuntu Mono", monospace, emoji;
    --iconFontFamily: "remixicon";
    --txtPrimaryColor: #e4e4e7;
    --txtHintColor: rgb(161 161 170);
    --txtDisabledColor: rgb(161 161 170 / 60%);
    --primaryColor: #00dc82;
    --baseColor: rgb(12 12 13);
    --bodyColor: rgb(12 12 13);
    --baseAlt1Color: #1c1c1f;
    --baseAlt2Color: #27272a;
    --baseAlt3Color: #27272a;
    --baseAlt4Color: #3e3e46;
    --infoColor: #026baa;
    --infoAltColor: #06293e;
    --successColor: #00dc82;
    --successAltColor: #044d2f;
    --dangerColor: #d50156;
    --dangerAltColor: #680b32;
    --warningColor: #ac8d0f;
    --warningAltColor: #463908;
    --overlayColor: rgb(22 22 25 / 60%);
    --tooltipColor: #1c1c1f;
    --shadowColor: rgba(0, 0, 0, .4);
    
    --baseRadius: 0.5rem;
    --lgRadius: 1rem;
    --btnRadius: 0.375rem;
    accent-color: var(--primaryColor);
}



hr {
    background: var(--baseAlt2Color);
}

.page-header-wrapper {
    background-color: rgb(22 22 25);
}

.panel {
    box-shadow: none;
}

.main-menu .menu-item.active, .main-menu .menu-item.current-route {
    color: var(--primaryColor);
}

.btn {
    color: var(--baseColor);
}

.btn.btn-outline {
    background-color: transparent;
}

.label.label-primary {
    background: var(--txtPrimaryColor);
}



.form-field.disabled label, .form-field.disabled .tinymce-wrapper, .form-field.disabled .code-editor, .form-field.disabled .select .selected-container, .select .form-field.disabled .selected-container, .form-field.disabled input, .form-field.disabled select, .form-field.disabled textarea {
    box-shadow: inset 0 0 0 var(--btnHeight) var(--overlayColor);
}

.form-field.form-field-toggle input[type=radio]:checked~label:before, .form-field.form-field-toggle input[type=checkbox]:checked~label:before {
    background: var(--primaryColor);
}



.thumb {
    --tile-color:  var(--baseAlt1Color);
    --tile-size: 12px;
    
    background-color: var(--baseAlt2Color);
    background-image: linear-gradient(45deg, var(--tile-color) 25%, transparent 25%, transparent 75%, var(--tile-color) 75%, var(--tile-color)), linear-gradient(45deg, var(--tile-color) 25%, transparent 25%, transparent 75%, var(--tile-color) 75%, var(--tile-color));
background-size: var(--tile-size) var(--tile-size);
  background-position: 0 0, calc(var(--tile-size) / 2) calc(var(--tile-size) / 2);
}

.overlay-panel .panel-header .overlay-close {
    color: var(--bodyColor);
    opacity: 1;
}

.sidebar-list-item.active {
    box-shadow: inset 0 0 0 1px var(--baseAlt2Color);
}

.docs-sidebar .sidebar-item.active {
    box-shadow: inset 0 0 0 1px var(--baseAlt2Color);
    background-color: var(--baseAlt1Color);
}

.docs-sidebar .sidebar-item:focus-visible, .docs-sidebar .sidebar-item:hover {
    background-color: var(--baseAlt1Color);
}

.docs-sidebar .sidebar-item:active {
    background-color: var(--baseAlt2Color);
}

.provider-card {
    border-color: var(--baseAlt2Color);
}



.app-tooltip {
    padding: .4em .8em;
}

.code-editor .cm-editor .cm-tooltip-autocomplete {
    background-color: var(--tooltipColor);
    border: 1px solid var(--baseAlt2Color);
    border-radius: var(--baseRadius);
}

.code-editor .cm-editor .cm-tooltip-autocomplete ul li {
    padding: .4em .8em;
    border-radius: var(--btnRadius) !important;
}

.code-editor .cm-editor .cm-tooltip-autocomplete ul li[aria-selected] {
    background: var(--primaryColor);
    color: var(--bodyColor);
}

.code-wrapper {
    border: 1px solid var(--baseAlt2Color);
    border-radius: var(--baseRadius);
}

.code-wrapper > code, .ͼb {
    color: #E5C07B !important;
}

.prism-light .token.atrule .token.rule, .prism-light .token.combinator, .prism-light .token.keyword, .prism-light .token.operator, .prism-light .token.pseudo-class, .prism-light .token.pseudo-element, .prism-light .token.selector, .prism-light .token.unit {
    color: #5fb6ff;
}

.prism-light .token.attr-value, .prism-light .token.color, .prism-light .token.inserted, .prism-light .token.selector .token.value, .prism-light .token.string, .prism-light .token.string .token.url-link, .ͼe {
    color: #98C379;
}

.prism-light .token.punctuation, .code-editor .cm-editor {
    color: #ABB2BF;
}

.prism-light .token.atrule .token.rule, .prism-light .token.combinator, .prism-light .token.keyword, .prism-light .token.operator, .prism-light .token.pseudo-class, .prism-light .token.pseudo-element, .prism-light .token.selector, .prism-light .token.unit {
    color: #C678DD;
}

.prism-light .token.operator {
    color: #56B6C2;
}

.prism-light .token.variable {
    color: #E5C07B;
}

.prism-light .token.class-name, .prism-light .token.key, .prism-light .token.parameter, .prism-light .token.property, .prism-light .token.property-access {
    color: #E06C75;
}

.prism-light .token.cdata, .prism-light .token.comment, .prism-light .token.doctype, .prism-light .token.prolog {
    color: #7F848E;
}

.prism-light .token.function, .prism-light .token.selector .token.class, .prism-light .token.selector .token.id {
    color: #61AFEF;
}

.prism-light .token.attr-name, .prism-light .token.boolean, .prism-light .token.boolean.important, .prism-light .token.constant, .prism-light .token.number, .prism-light .token.selector .token.attribute {
    color: #D19A66;
}
```

**Comment by sergio9929** [comment]
I published it as an userstyle here: https://userstyles.world/style/10395/pocketbase-dark-theme

The theme detects if you are using pocketbase by looking for "/_/" in the url, so it will apply to all pocketbase instances regardless of the domain.
![image](https://github.com/pocketbase/pocketbase/assets/29752861/dac48275-f023-485a-8334-070a9394f4c9)

**Comment by Teraskull** [comment]
@sergio9929 My take on the color scheme based on your userstyle:

https://gist.github.com/Teraskull/34f639fe5e19c54ed77035e2e1146c21

Used the [Tailwind 3.3 color scheme](https://tailwindcss.com/docs/customizing-colors). This improves contrast, readability, and reduces eyestrain.

Screenshots:
![collection page](https://github.com/pocketbase/pocketbase/assets/24798198/35128dee-6aed-47f4-a8c1-8409b8c4f74b)
![api docs sidebar page](https://github.com/pocketbase/pocketbase/assets/24798198/41fa2de5-0e0b-4e07-8123-c68189abc833)
![logs page](https://github.com/pocketbase/pocketbase/assets/24798198/a09ef492-f274-4396-bb49-0fe3423d1753)

Maybe Pocketbase will take some inspiration when implementing the official theme :)

**Comment by sergio9929** [comment]
I've fixed some bugs in my theme and I'm sending you the list of changes so you don't have to search for them:

1. Fixed chart date visibility and colors:

    ```css
    .chart-canvas {
        filter: invert(.9) hue-rotate(335deg);
    }
    ```

3. Fixed caret visibility on API rules and search filter:

    ```css
    html, .cm-editor .cm-content, .cm-editor .cm-line {
        caret-color: var(--txtPrimaryColor) !important;
    }
    ```

4. Improved API rules and search filter code highlighting:

    - added new class `.ͼe` in

        ```css
        .prism-light .token.attr-value, .prism-light .token.color, .prism-light .token.inserted, .prism-light .token.selector .token.value, .prism-light .token.string, .prism-light .token.string .token.url-link, .ͼe {
            color: #98C379;
        }
         ```
    - added classs `.ͼc, .ͼd` in:

        ```css
        .prism-light .token.attr-name, .prism-light .token.boolean, .prism-light .token.boolean.important, .prism-light .token.constant, .prism-light .token.number, .prism-light .token.selector .token.attribute, .ͼc, .ͼd {
            color: #D19A66;
        }
        ```

5. Additional improvements:

    ```css
    .unlock-overlay {
        background-color: rgba(0, 0, 0, .2) !important;
    }
    
    .lock-toggle {
        background-color: var(--baseAlt2Color) !important;
    }
    ```

**Comment by sergio9929** [comment]
> @sergio9929 My take on the color scheme based on your userstyle:
> 
> https://gist.github.com/Teraskull/34f639fe5e19c54ed77035e2e1146c21
> 
> Used the [Tailwind 3.3 color scheme](https://tailwindcss.com/docs/customizing-colors). This improves contrast, readability, and reduces eyestrain.
> 
> Screenshots: ![collection page](https://user-images.githubusercontent.com/24798198/256690248-35128dee-6aed-47f4-a8c1-8409b8c4f74b.png) ![api docs sidebar page](https://user-images.githubusercontent.com/24798198/256690270-41fa2de5-0e0b-4e07-8123-c68189abc833.png) ![logs page](https://user-images.githubusercontent.com/24798198/256690710-a09ef492-f274-4396-bb49-0fe3423d1753.png)
> 
> Maybe Pocketbase will take some inspiration when implementing the official theme :)

I've fixed some bugs in my theme and I'm sending you the list of changes so you don't have to search for them:

1. Fixed chart date visibility and colors:

    ```css
    .chart-canvas {
        filter: invert(.9) hue-rotate(335deg);
    }
    ```

3. Fixed caret visibility on API rules and search filter:

    ```css
    html, .cm-editor .cm-content, .cm-editor .cm-line {
        caret-color: var(--txtPrimaryColor) !important;
    }
    ```

4. Improved API rules and search filter code highlighting:

    - added new class `.ͼe` in

        ```css
        .prism-light .token.attr-value, .prism-light .token.color, .prism-light .token.inserted, .prism-light .token.selector .token.value, .prism-light .token.string, .prism-light .token.string .token.url-link, .ͼe {
            color: #98C379;
        }
         ```
    - added classs `.ͼc, .ͼd` in:

        ```css
        .prism-light .token.attr-name, .prism-light .token.boolean, .prism-light .token.boolean.important, .prism-light .token.constant, .prism-light .token.number, .prism-light .token.selector .token.attribute, .ͼc, .ͼd {
            color: #D19A66;
        }
        ```

5. Additional improvements:

    ```css
    .unlock-overlay {
        background-color: rgba(0, 0, 0, .2) !important;
    }
    
    .lock-toggle {
        background-color: var(--baseAlt2Color) !important;
    }
    ```
