### ISSUE TITLE
facing CORS error when hosting via docker but not with the binary on host system

### ISSUE THREAD

**Issue by meta-boy** [pocketbase/pocketbase#4883]
I'm using cloudflare tunnels to expose my pocketbase instance over internet.

I have the following Dockerfile
```
FROM alpine:latest

ARG PB_VERSION=0.22.11

RUN apk add --no-cache \
    unzip \
    ca-certificates

# download and unzip PocketBase
ADD https://github.com/pocketbase/pocketbase/releases/download/v${PB_VERSION}/pocketbase_${PB_VERSION}_linux_amd64.zip /tmp/pb.z>
RUN unzip /tmp/pb.zip -d /pb/

# create necessary directories
RUN mkdir -p /pb/pb_data /pb/pb_migrations /pb/pb_hooks /pb/pb_logs

EXPOSE 8080

# start PocketBase with CORS configuration
CMD ["/pb/pocketbase", "serve", "--http=0.0.0.0:8080"]
```
and this docker-compose.yaml
```
version: '3'
services:
  pocketbase:
    image: pocket-base
    container_name: pocketbase
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - /path/to/pb_data:/pb/pb_data
      - /path/to/pb_migrations:/pb/pb_migrations
      - /path/to/pb_hooks:/pb/pb_hooks
      - /path/to/pb_logs:/pb/pb_logs
```
my application running on localhost fails with CORS error while the same request on the same application works fine, the only change being pocketbase now runs via the binary on the host system.
