### ISSUE TITLE
App Settings can't be saved (>v.0.20)

### ISSUE THREAD

**Issue by OskarPetersilie** [pocketbase/pocketbase#5751]
Hey i am using pocketbase for several applications i create.

The newest app sends emails via smtp. While configuring smtp in my poketbase i stumbled upon 400 requests without any data while trying to update the app setting.

I tested in v0.21 and v0.22. It does not work and i cant find any error messages.

Works with v.0.20

my docker-compos.yml which i use to manage the pb

```
services:
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:0.20 #change to 0.22 or 0.21 for tests
    container_name: gbl-pocketbase
    restart: unless-stopped
    ports:
      - "8103:8090"
    volumes:
      - ./db/pb_data:/pb_data
      - ./db/pb_public:/pb_public
      - ./db/pb_migration:/pb_migration
      - ./db/pb_hooks:/pb_hooks
    healthcheck: #optional (recommended) since v0.10.0
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
  ```
   

 Application and Mail Settings tabs are not working.
   
   ```

   fetch("https://myUrl/myAppDomainPath/api/settings", {
  "headers": {
    "accept": "*/*",
    "accept-language": "en-US",
    "authorization": "auth",
    "cache-control": "no-cache",
    "content-type": "application/json",
    "pragma": "no-cache",
    "sec-ch-ua": "\"Chromium\";v=\"130\", \"Google Chrome\";v=\"130\", \"Not?A_Brand\";v=\"99\"",
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": "\"Windows\"",
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "same-origin",
    "Referer": "https://prod.webtitans.dev/feed-management/_/",
    "Referrer-Policy": "strict-origin-when-cross-origin"
  },
  "body": "{\"meta\":{\"appName\":\"Acmed\",\"appUrl\":\"http://localhost:8090\",\"hideControls\":false,\"senderName\":\"Support\",\"senderAddress\":\"support@example.com\",\"verificationTemplate\":{\"body\":\"<p>Hello,</p>\\n<p>Thank you for joining us at {APP_NAME}.</p>\\n<p>Click on the button below to verify your email address.</p>\\n<p>\\n  <a class=\\\"btn\\\" href=\\\"{ACTION_URL}\\\" target=\\\"_blank\\\" rel=\\\"noopener\\\">Verify</a>\\n</p>\\n<p>\\n  Thanks,<br/>\\n  {APP_NAME} team\\n</p>\",\"subject\":\"Verify your {APP_NAME} email\",\"actionUrl\":\"{APP_URL}/_/#/auth/confirm-verification/{TOKEN}\",\"hidden\":false},\"resetPasswordTemplate\":{\"body\":\"<p>Hello,</p>\\n<p>Click on the button below to reset your password.</p>\\n<p>\\n  <a class=\\\"btn\\\" href=\\\"{ACTION_URL}\\\" target=\\\"_blank\\\" rel=\\\"noopener\\\">Reset password</a>\\n</p>\\n<p><i>If you didn't ask to reset your password, you can ignore this email.</i></p>\\n<p>\\n  Thanks,<br/>\\n  {APP_NAME} team\\n</p>\",\"subject\":\"Reset your {APP_NAME} password\",\"actionUrl\":\"{APP_URL}/_/#/auth/confirm-password-reset/{TOKEN}\",\"hidden\":false},\"confirmEmailChangeTemplate\":{\"body\":\"<p>Hello,</p>\\n<p>Click on the button below to confirm your new email address.</p>\\n<p>\\n  <a class=\\\"btn\\\" href=\\\"{ACTION_URL}\\\" target=\\\"_blank\\\" rel=\\\"noopener\\\">Confirm new email</a>\\n</p>\\n<p><i>If you didn't ask to change your email address, you can ignore this email.</i></p>\\n<p>\\n  Thanks,<br/>\\n  {APP_NAME} team\\n</p>\",\"subject\":\"Confirm your {APP_NAME} new email address\",\"actionUrl\":\"{APP_URL}/_/#/auth/confirm-email-change/{TOKEN}\",\"hidden\":false}}}",
  "method": "PATCH"
});
```

Response

```
{"code":400,"message":"An error occurred while submitting the form.","data":{}}

`
