### ISSUE TITLE
Proposal: Email validation/confiration routes links not have #

### ISSUE THREAD

**Issue by RabbITCybErSeC** [pocketbase/pocketbase#6815]
Hi team, 

Thank you for all the work on Pocketbase it has been an awesome ride building with Pocketbase. Now that we are deploying to production I am putting Pocketbase behind a Traefik reverse proxy. For new users to confirm their email they will be routed to links like: `/_/#/auth/confirm-verification/{TOKEN}`

Would it be possible to change this route to let's say, e.g. `/_/auth/confirm-verification/{TOKEN}`. In this way, users can setup their Traefik (example below) to block `/_/` and only expose the `/_/auth` for email validation. In this way, the entire  dashboard does not have to be exposed. I know it is possible to make this a custom implementation. But why not make this a default setting?

The below would is unfortunately not possible as `#` is client-side and never sent to the server. 
```yaml
  app-backend:
    container_name: pocketbase-backend
    image: pocketbase-backend:latest
    restart: unless-stopped
    ports:
      - "8090:8090"
    networks:
      - traefik
    volumes:
      - ./app-data:/app-data
    labels:
      # General
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      # Routing
      - "traefik.http.routers.backend.entrypoints=web-secure"
      - "traefik.http.routers.backend.rule=Host(`api.nl`) && (PathPrefix(`/api/`) || PathPrefix(`/_/#/auth/confirm-verification/`) || PathPrefix(`/_/#/auth/confirm-password-reset/`) || PathPrefix(`/_/#/auth/confirm-email-change/`))"
      - "traefik.http.routers.backend.tls=true"
      - "traefik.http.routers.backend.tls.certresolver=transip"
      - "traefik.http.services.backend.loadBalancer.server.port=8090"
```

Happy to hear your thoughts. 

Best.
